version: '2'
services:
  dns:
    restart: always
    image: davedeveloper/dnsmasq-rest-api-docker:latest
    volumes:
      - ./config.php:/opt/dnsmasq-rest-api/www/config.php
    ports:
      - "53:53/udp"
      - "5380:80/tcp"
    networks:
      LocalDevNet:
        ipv4_address: 172.27.0.254
networks:
  LocalDevNet:
    external: true
