version: '2'
services:
  dns:
    restart: always
    image: davedeveloper/dnsmasq-rest-api-docker:latest
    volumes:
      - ./config.php:/opt/dnsmasq-rest-api/www/config.php
    ports:
      - "53:53/udp"
      - "5380:80/tcp"
    networks:
      - LocalDevNet
  proxy:
    restart: always
    ports:
      - "1080:1080"
    image: kallqvist/microsocks
    networks:
      - LocalDevNet
networks:
  LocalDevNet:
    name: LocalDevNet
    external: true
    ipam:
     config:
       - subnet: 192.168.18.0/24
         gateway: 192.168.18.1
         aux_addresses:
          dns: 192.168.18.253
          proxy: 192.168.18.254

